### ISSUE TITLE
右键菜单“Click(Refresh)”功能报错

### ISSUE THREAD

**Issue by lovexiaov** [DroidTesting/android-uiautomatorviewer#1]
RT，使用时界面没有刷新，命令行报如下错误：
```
Unhandled event loop exception during blocked modal context.
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
	at org.eclipse.swt.SWT.error(SWT.java:4441)
	at org.eclipse.swt.SWT.error(SWT.java:4356)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:139)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4147)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3764)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:175)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:390)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:527)
	at com.android.uiautomator.actions.ScreenshotAction.run(ScreenshotAction.java:86)
	at com.android.uiautomator.UiAutomatorView$3$6.widgetSelected(UiAutomatorView.java:328)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)
	at org.eclipse.jface.window.Window.open(Window.java:808)
	at com.android.uiautomator.UiAutomatorViewer.main(UiAutomatorViewer.java:88)
Caused by: java.lang.NullPointerException
	at com.android.uiautomator.UiAutomatorViewer$1.run(UiAutomatorViewer.java:113)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
	... 16 more
java.lang.NullPointerException
	at com.android.uiautomator.actions.ScreenshotAction.showError(ScreenshotAction.java:109)
	at com.android.uiautomator.actions.ScreenshotAction.run(ScreenshotAction.java:104)
	at com.android.uiautomator.UiAutomatorView$3$6.widgetSelected(UiAutomatorView.java:328)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)
	at org.eclipse.jface.window.Window.open(Window.java:808)
	at com.android.uiautomator.UiAutomatorViewer.main(UiAutomatorViewer.java:88)

```

**Comment by lovexiaov** [comment]
看了一下代码，发现是整合代码的时候， 该功能创建了一个新的 `UiAutomatorViewer` 实例，而没有复用
 UiAutomatorViewer.java 类 `main` 方法中创建的 `UiAutomatorViewer` 实例导致的。
该问题已在 https://github.com/DroidTesting/android-uiautomatorviewer/commit/b0090fd5765dd4aea9c2695015024c15bc86b1fb 中修复。

**Comment by lovexiaov** [comment]
其实，报此 bug 的时候还没有添加右键菜单功能o(╯□╰)o！
